apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-ingress
  namespace: demo
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: demo.local
      http:
        paths:
          - path: /hello
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 80
          - path: /info
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 80
          - path: /ready
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 80
          - path: /toggle-health
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 80
          - path: /toggle-ready
            pathType: Prefix
            backend:
              service:
                name: demo-service
                port:
                  number: 80